// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutocompleteController from "./autocomplete_controller"
application.register("autocomplete", AutocompleteController)

import DefaultScoresheetController from "./default_scoresheet_controller"
application.register("default-scoresheet", DefaultScoresheetController)

import FiveCrownsController from "./five_crowns_controller"
application.register("five-crowns", FiveCrownsController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MexicanTrainController from "./mexican_train_controller"
application.register("mexican-train", MexicanTrainController)

import OhHellController from "./oh_hell_controller"
application.register("oh-hell", OhHellController)

import RulesController from "./rules_controller"
application.register("rules", RulesController)

import SkyjoController from "./skyjo_controller"
application.register("skyjo", SkyjoController)
