name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        # wait for PG to be ready
        options: >-
          --health-cmd "pg_isready -U rails"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://rails:password@localhost:5432/app_test

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3'
          bundler-cache: true  # caches gems based on Gemfile.lock

      # If your tests need libvips (ActiveStorage variants), keep this.
      - name: System deps
        run: sudo apt-get update -qq && sudo apt-get install -y libvips

      - name: Prepare DB
        run: bin/rails db:prepare

      # Rails default (Minitest)
      - name: Run tests (Minitest)
        run: bin/rails test
