name: CI

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: rails
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd="pg_isready -U rails -d app_test"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    env:
      RAILS_ENV: test
      DATABASE_URL: postgres://rails:password@localhost:5432/app_test

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.5'
          bundler-cache: true

      - name: System deps
        run: sudo apt-get update -qq && sudo apt-get install -y libvips

      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'

      - name: Install JS deps
        run: yarn install --frozen-lockfile

      # Fail fast if CSS build breaks:
      - name: Build CSS
        run: yarn build:css

      - name: Prepare DB
        run: bin/rails db:prepare

      - name: Run tests (Minitest)
        run: bin/rails test
