five_crowns:
  long_game:
    label: "Long game - From 3 to King, and then back."
    type: "checkbox"
  early_finish:
    label: "Early finish - Don't wait for your hand to be completed before finishing."
    type: "checkbox"
    subrules:
      double_if_not_lowest:
        label: "If you finish first without the lowest score, double it!"
        type: "checkbox"
