number_of_rounds: 11
early_finish: false
current_round: 1
cards_per_round:
  1: 3
  2: 4
  3: 5
  4: 6
  5: 7
  6: 8
  7: 9
  8: 10
  9: 11
  10: 12
  11: 13
  12: 12
  13: 11
  14: 10
  15: 9
  16: 8
  17: 7
  18: 6
  19: 5
  20: 4
  21: 3
wild_cards:
  1: 3
  2: 4
  3: 5
  4: 6
  5: 7
  6: 8
  7: 9
  8: 10
  9: Jack
  10: Queen
  11: King
  12: Queen
  13: Jack
  14: 10
  15: 9
  16: 8
  17: 7
  18: 6
  19: 5
  20: 4
  21: 3
min_players: 2
max_players: 7
starting_scores: 0
